# Introduction to Data Science: Sorting and Filtering Data
Please complete this assignment with your small group. Discussion is encouraged and a completed version is due before the next class.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

We are going to create a variable to store our data on course staff. 
The argument given to `read_csv` is the path to the file containing our data.

In [2]:
staff_data = pd.read_csv('./data/fall2024_python_staff.csv')
staff_data

,first_name,last_name,major,year,graduated,school,favorite_number
0,Kallee,Gallant,physics,NaN,True,Columbia,9
1,Abby,Pitcairn,computer science,senior,False,University of Southern Maine,7
2,Peter,Fitton,physics,junior,False,University of Southern Maine,1
3,Shreya,Singh,computer science,junior,False,Stanford,3
4,Silas,Pillsbury,philosophy,NaN,True,St. Johns College,6

## Sorting DataFrames

The `df.sort_index` and `df.sort_values` methods allow us to manipulate the arrangement of our dataframe.

The `df.sort_index` method acts on the bolded column names at the top of the dataframe. These are not actual data points, but rather labels to help us organize our table.

In [25]:
import pandas as pd
staff_data = pd.read_csv('./data/fall2024_python_staff.csv')

staff_data.sort_values("first_name")

,first_name,last_name,major,year,graduated,school,favorite_number
1,Abby,Pitcairn,computer science,senior,False,University of Southern Maine,7
0,Kallee,Gallant,physics,NaN,True,Columbia,9
2,Peter,Fitton,physics,junior,False,University of Southern Maine,1
3,Shreya,Singh,computer science,junior,False,Stanford,3
4,Silas,Pillsbury,philosophy,NaN,True,St. Johns College,6

Notice how the column headers are now arranged in alphabetical order.

Now let's pick a random group of 3 staff members to grade assignments this week.

In [4]:
graders = staff_data.sample(3)
graders

,first_name,last_name,major,year,graduated,school,favorite_number
4,Silas,Pillsbury,philosophy,NaN,True,St. Johns College,6
2,Peter,Fitton,physics,junior,False,University of Southern Maine,1
1,Abby,Pitcairn,computer science,senior,False,University of Southern Maine,7

### Q.1: How would we organize our sample from the data frame based on the order people were added to it?

In [ ]:
# YOUR CODE HERE
staff_data.sort_values(axis = 0)

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

Notice this organization is the same as what pandas defaulted to when we loaded in our data.

This function allows us to unscramble the rows, if we need to maintain the order entries were added to the dataframe.

### Q.2 Describe a scenario where it is essential to maintain the order that people were added to the dataframe

### A.2 YOUR ANSWER HERE

### Q.3 Please organize our staff roster in alphabetical order by first name

In [6]:
# YOUR CODE HERE
import pandas as pd
staff_data = pd.read_csv('./data/fall2024_python_staff.csv')

staff_data.sort_values("first_name")

,first_name,last_name,major,year,graduated,school,favorite_number
1,Abby,Pitcairn,computer science,senior,False,University of Southern Maine,7
0,Kallee,Gallant,physics,NaN,True,Columbia,9
2,Peter,Fitton,physics,junior,False,University of Southern Maine,1
3,Shreya,Singh,computer science,junior,False,Stanford,3
4,Silas,Pillsbury,philosophy,NaN,True,St. Johns College,6

## Using Conditions to Filter DataFrames

In [7]:
staff_data = pd.read_csv('./data/fall2024_python_staff.csv')

Let's say that we need to use Kallee's data in a function we are writing. We will first isolate Kallee's data using data frame filtering based on first name.

In [8]:
# example to retrieve Kallee's information
kallee_data = staff_data[staff_data.first_name == "Kallee"]
display(kallee_data)

  first_name last_name    major year  graduated    school  favorite_number
0     Kallee   Gallant  physics  NaN       True  Columbia                9

Now let's try to combine two different conditions. Here we want to find staff members who have graduated and have an even favorite number.

In [9]:
# example to filter on multiple conditions
# is_graduated is a list of booleans
# A value at a specified index n is true if the nth person graduated
is_graduated = (staff_data.graduated)
fav_num_even = (staff_data.favorite_number % 2 == 0)

staff_data[is_graduated & fav_num_even]

,first_name,last_name,major,year,graduated,school,favorite_number
4,Silas,Pillsbury,philosophy,NaN,True,St. Johns College,6

Let's say that we have represented the menu at our favorite restaurant in a csv file:

In [10]:
menu = pd.read_csv('./data/menu.csv')
menu

                 item  calories  price  vegetarian  seasonal
0     Chicken Alfredo      1200  15.99       False     False
1     Pumpkin Risotto       800  18.99        True      True
2    Margherita Pizza      1500  10.99        True     False
3  House Potato Salad       600   7.49       False     False
4    Carnitas Burrito      1300  13.99       False     False
5         Lentil Soup       250   5.49        True     False
6         Texas Toast       600   3.99        True     False

### Q.4 What are the three highest calorie foods on this restaurant's menu?

In [17]:
import pandas as pd
menu = pd.read_csv('./data/menu.csv')
print(menu.sort_values('calories')[-3:])

               item  calories  price  vegetarian  seasonal
0   Chicken Alfredo      1200  15.99       False     False
4  Carnitas Burrito      1300  13.99       False     False
2  Margherita Pizza      1500  10.99        True     False

### A.4 YOUR ANSWER HERE

### Q.5 What vegetarian items have less than 1000 calories and cost less than $15?

In [23]:
import pandas as pd
menu = pd.read_csv('./data/menu.csv')
cal = (menu.calories < 1000)
price = (menu.price < 15)
menu[cal & price]

                 item  calories  price  vegetarian  seasonal
3  House Potato Salad       600   7.49       False     False
5         Lentil Soup       250   5.49        True     False
6         Texas Toast       600   3.99        True     False

### A.5 YOUR ANSWER HERE